fragment IndexPageParts on IndexPage {
  __typename
  header
  description
  image
  PreviewVideo
  form {
    __typename
    placeholder
    buttonText
    text
  }
  body
}

fragment AboutPageParts on AboutPage {
  __typename
  header
  button {
    __typename
    text
    link
  }
  SatisfiedClients
  ActiveEngagement
  SuccessProjects
  AwardsWinning
  body
}

fragment BlogsParts on Blogs {
  __typename
  title
  publishDate
  image
  body
}

fragment SiteParts on Site {
  __typename
  siteName
  description
  favicon
}
